<ul class="nav metismenu" id="sidebar-menu">
    <?php foreach ($this->navigation('navigation')->getContainer() as $page){?>
        <li class="<?php echo ("http://".$_SERVER['SERVER_NAME'].$page->getHref() == $this->serverUrl(true)) ? 'active' : '' ?>">
            <a href="<?php echo $page->getHref() ?>"> <i class="fa fa-th-large"></i> <?php echo $page->getLabel() ?> <?php echo $page->hasPages() ? '<i class="fa arrow"></i> ' : '' ?></a>
            <?php if ($page->hasPages()){ ?>
            <ul>
                <?php foreach ($page->getPages() as $child){ ?>
                <li class="<?php echo ("http://".$_SERVER['SERVER_NAME'].$child->getHref() == $this->serverUrl(true)) ? 'active' : '' ?>">
                    <a href="<?php echo $child->getHref() ?>">
                        <?php
                        echo $child->getLabel()
                        ?>
                    </a>
                </li>
                <?php } ?>
            </ul>
            <?php } ?>
        </li>
    <?php } ?>
</ul>