<?php
$title = 'Templates';
$this->headTitle($title);
?>
<div class="title-block">
    <div class="row">
        <div class="col-md-6">
            <h3 class="title"> <?php echo $this->escapeHtml($title); ?> <a
                        href="<?php echo $this->url('mail/templates/add', array('action'=>'add'), true);?>" class="btn btn-primary btn-sm rounded-s">
                    <em class="fa fa-plus"></em> Add New Template
                </a>
            </h3>
        </div>
    </div>
</div>
<div class="row">
<div class="col-md-12">
<div class="card">
<div class="card-block">
<section class="example">
<div class="table-responsive">
<table class="table table-striped table-bordered table-hover">
  <thead>
  <tr>
      <th>#</th>
      <th>Name</th>
      <th class="tright">Actions</th>
  </tr>
  </thead>
  <tbody>
    <?php foreach ($this->templates as $template) : ?>
        <tr>
            <td><?php echo $template->getId();?></td>
            <td><?= $this->escapeHtml($template->getName()) ?></td>
            <td class="tright">
              <a class="btn btn-pill-left btn-secondary" href="javascript:void(0)" data-toggle="modal" data-target="#deleteModal" data-content="<?php echo $partial['content']?>" data-title="<?php echo $partial['name'] ?>">
                  <em class="fa fa-eye"></em> Preview</a>
              <a class="btn btn-info btn-secondary" href="<?= $this->url('mail/templates/edit', ['action' => 'edit', 'id' => $template->getId()]) ?>">
                  <em class="fa fa-edit"></em>Edit</a>
              <a class="btn btn-pill-right btn-danger remove_partial" href="<?= $this->url('mail/templates/delete', ['action' => 'delete', 'id' => $template->getId()]) ?>">
                  <em class="fa fa-trash-o"></em> Delete
              </a>

            </td>
        </tr>
    <?php endforeach; ?>
  </tbody>
</table>
</div>
</section>
</div>
</div>
</div>
</div>
