<?php
$title = 'Templates';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('mail/templates/add', array('action'=>'add'), true);?>">Create new template</a>
</p>

<table class="table">
    <tr>
        <th>Nombre</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->templates as $template) : // <-- change here! ?>
        <tr>
            <td><?= $this->escapeHtml($template->getTitle()) ?></td>
            <td>
                <a href="<?= $this->url('mail/templates/edit', ['action' => 'edit', 'id' => $template->getId()]) ?>">Edit</a>
                <a href="<?= $this->url('mail/templates/delete', ['action' => 'delete', 'id' => $template->getId()]) ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
