<?php
$title = 'Mail Partials';
$this->headTitle($title);
echo $this->flashMessenger()->render();
?>
<div class="title-block">
    <div class="row">
        <div class="col-md-6">
            <h3 class="title"> <?php echo $this->escapeHtml($title); ?> <a
                        href="<?php echo $this->url('partials/add') ?>" class="btn btn-primary btn-sm rounded-s">
                    <em class="fa fa-plus"></em> Add New Partial
                </a>
            </h3>
        </div>
    </div>
</div>
<section class="section">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-block">
                    <section class="example">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th class="tright">Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                if ($this->total > 0):
                                    foreach ($this->partials as $partial) : ?>
                                        <tr>
                                            <td><?php echo $partial['id'] ?></td>
                                            <td><?php echo $partial['name'] ?></td>
                                            <td class="tright">
                                                <a class="btn btn-pill-left btn-secondary" href="javascript:void(0)" data-toggle="modal" data-target="#deleteModal" data-content="<?php echo $partial['content']?>" data-title="<?php echo $partial['name'] ?>">
                                                    <em class="fa fa-eye"></em> Preview</a>
                                                <a class="btn btn-info btn-secondary" href="<?php echo $this->url('partials/edit', ['id' => $partial['id']]) ?>">
                                                    <em class="fa fa-edit"></em>Edit</a>
                                                <a class="btn btn-pill-right btn-danger remove_partial" href="javascript:void(0)" data-toggle="modal" data-target="#deleteModal" data-id="<?php echo $partial['id'] ?>">
                                                    <em class="fa fa-trash-o"></em> Delete
                                                </a>
                                            </td>
                                        </tr>
                                        <?php
                                    endforeach;
                                else:
                                    ?>
                                    <tr>
                                        <td colspan="3">There are no results
                                        </td>
                                    </tr>
                                    <?php
                                endif;
                                ?>
                                </tbody>
                            </table>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
</section>

<form action="#" method="POST" name="deletePartialForm" id="deletePartialForm">
    <input type="hidden" id="partialId" name="partialId"/>
    <input type="hidden" id="del" name="del" value="no">
</form>
<?php
$this->inlineScript()->captureStart();
echo <<<JS
$('.remove_partial').on('click', function(e){
    var id = $(this).data('id');
    $('#deletePartialForm').attr('action', '/admin/mail/partials/delete/'+id);
    $('#deletePartialForm input[id=partialId]').val(id);
    $('#deletePartialForm input[id=del]').val('yes');
});
$('#cancelDeleteModal').click(function(){
    $('#deletePartialForm input[id=partialId]').val('');
    $('#deletePartialForm input[id=del]').val('no');
});
$('#confirmDeleteModal').click(function(){
    $('#deletePartialForm').trigger('submit');
});
JS;
$this->inlineScript()->captureEnd();
?>

<!-- Modal -->
<div class="modal fade" id="deleteModal" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header modal-header-warning">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Delete Partial</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete the selected partial?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal" id="confirmDeleteModal">Delete it!</button>
                <button type="button" class="btn btn-default" data-dismiss="modal" id="cancelDeleteModal">Cancel</button>
            </div>
        </div>

    </div>
</div>