<?php
$title = 'Mail Partials';
$this->headTitle($title);

?>
<div class="title-block">
    <div class="row">
        <div class="col-md-6">
            <h3 class="title"> <?php echo $this->escapeHtml($title); ?> <a href="<?php echo $this->url('partials/add') ?>" class="btn btn-primary btn-sm rounded-s">
                    Add New Partial
                </a>
            </h3>
        </div>
    </div>
</div>
<section class="section">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-block">
                    <section class="example">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                if($this->total > 0):
                                    foreach ($this->partials as $partial) : ?>
                                    <tr>
                                        <td><?php echo $partial->getId()?></td>
                                        <td><?php echo $partial->getName()?></td>
                                        <td>
                                            <a href="<?php echo $this->url('partials/edit', ['id' => $partial->getId()]) ?>">Edit</a>
                                            <a href="<?php echo $this->url('partials/delete', ['id' => $partial->getId()]) ?>">Delete</a>
                                        </td>
                                    </tr>
                                <?php
                                    endforeach;
                                else:
                                ?>
                                    <tr>
                                        <td colspan="3">There are no results
                                        </td>
                                    </tr>
                                <?php
                                endif;
                                ?>
                                </tbody>
                            </table>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
</section>
